excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Source/Frameworks
  - CaptainFlint/Classess/Controls/Progress/Library
# implicitly
line_length: 450
function_body_length:
  - 300 # warning
  - 400 # error
disabled_rules:
  - weak_delegate
  - class_delegate_protocol
